language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
  - python setup.py test
script:
  - python bin/sledge tests/pages/
notifications:
  email: false