package:
  name: Sledge
  language: Python
  version: 1.0
  license: MIT
  copyright: 2019 Frame Studios
  authors:
    - Frame Studios
    - Caleb Pitan
  dependencies:
    - PyYAML
    - watchdog
    - colorama
    - termcolor
  description: Build and deploy websites faster than you can blink your eyes
  SCM: Git
  repository: https://github.com/framestd/sledge
  dist: sledge